### PR TITLE
Important Update

### PR DESCRIPTION
**Pull request by dentmaged**
Just an important update!

### CODE REVIEW

**Comment by dentmaged** [comment]
I don't see what you're talking about with #2

**Comment by TiTo-418** [comment]
Thanks! Good job!

**Comment by TiTo-418** [comment]
@dentmaged Thanks 4 all! Now you are a collaborator!

**Comment by dentmaged** [comment]
@TiTo-418 Wasn't I one before?

**Comment by TiTo-418** [comment]
@dentmaged No. Please push commmits to improve CardinalTiTo-Dent

**Comment by dentmaged** [comment]
@TiTo-418 My commits would be here from the original.

**Comment by TiTo-418** [comment]
@dentmaged Thanks dent! :')

**Pull request merged**
